In [ ]:
import numpy as np
x = np.ones((2, 3, 4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [4]:
x.shape

(2, 3, 4)

In [6]:
a = np.linspace(1, 10, 4)
a

array([ 1.,  4.,  7., 10.])

In [9]:
b = np.linspace(1, 10, 4, endpoint=False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [10]:
c = np.linspace(1, 10, 4)
c

array([ 1.,  4.,  7., 10.])

In [11]:
d = np.concatenate((a, b))
d

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [13]:
a = np.ones((2, 3, 4), dtype=np.int32)
a.reshape((3, 8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [15]:
a.resize((3, 8))
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
a = np.ones((2, 3, 4), dtype=np.int32)
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [17]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
b = a.flatten()
print(b)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [20]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [22]:
b = a.astype(np.float)
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [23]:
a = np.full((2, 3, 4), 25, dtype=np.int32)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [24]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

In [25]:
a = np.array([9, 8, 7, 6, 5])
a[2]

7

In [26]:
a[1:4:2]

array([8, 6])

In [27]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a[1, 2, 3]

23

In [29]:
a[0, 1, 2]

6

In [30]:
a[-1, -2, -3]

17

In [31]:
a[:, 1:3, :]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
a[:, :, ::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [34]:
a.mean()

11.5

In [35]:
a / a.mean()

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

In [36]:
np.abs(a)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
np.fabs(a)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [38]:
np.sqrt(a)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [39]:
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [40]:
np.log(a)

C:\Program Files\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015],
        [2.07944154, 2.19722458, 2.30258509, 2.39789527]],

       [[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
        [2.77258872, 2.83321334, 2.89037176, 2.94443898],
        [2.99573227, 3.04452244, 3.09104245, 3.13549422]]])

In [41]:
np.log10(a)

C:\Program Files\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 0.30103   , 0.47712125],
        [0.60205999, 0.69897   , 0.77815125, 0.84509804],
        [0.90308999, 0.95424251, 1.        , 1.04139269]],

       [[1.07918125, 1.11394335, 1.14612804, 1.17609126],
        [1.20411998, 1.23044892, 1.25527251, 1.2787536 ],
        [1.30103   , 1.32221929, 1.34242268, 1.36172784]]])

In [42]:
np.log2(a)

C:\Program Files\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 1.        , 1.5849625 ],
        [2.        , 2.32192809, 2.5849625 , 2.80735492],
        [3.        , 3.169925  , 3.32192809, 3.45943162]],

       [[3.5849625 , 3.70043972, 3.80735492, 3.9068906 ],
        [4.        , 4.08746284, 4.169925  , 4.24792751],
        [4.32192809, 4.39231742, 4.45943162, 4.52356196]]])

In [44]:
np.ceil(a)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [45]:
np.floor(a)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [46]:
np.modf(a)

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]), array([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],
 
        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]))

In [47]:
np.mod(a, 2)

array([[[0, 1, 0, 1],
        [0, 1, 0, 1],
        [0, 1, 0, 1]],

       [[0, 1, 0, 1],
        [0, 1, 0, 1],
        [0, 1, 0, 1]]], dtype=int32)

In [48]:
np.mod(a, 10)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 0, 1]],

       [[2, 3, 4, 5],
        [6, 7, 8, 9],
        [0, 1, 2, 3]]], dtype=int32)

In [49]:
a = np.arange(100).reshape(5, 20)
np.savetxt('a.csv', a, fmt='%d', delimiter=',')

In [50]:
np.savetxt('a1.csv', a, fmt='%.1f', delimiter=',')

In [51]:
b = np.loadtxt('a.csv', delimiter=',')

In [52]:
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [53]:
c = np.loadtxt('a.csv',dtype = np.int, delimiter=',')
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [54]:
a = np.arange(100).reshape(5, 10, 2)
a.tofile("b.dat", sep=",", format='%d')

In [55]:
a.tofile("c.dat", format='%d')

In [56]:
d = np.fromfile("b.dat", dtype=np.int, sep=",")
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
e = np.fromfile("b.dat", dtype=np.int, sep=",").reshape(5, 10, 2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [58]:
np.save("a.npy", a)

In [59]:
a = np.arange(100).reshape(5, 10, 2)
np.save("a.npy", a)

In [60]:
b = np.load("a.npy")
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [61]:
a = np.random.rand(3, 4, 5)
a

array([[[0.63889701, 0.90864459, 0.64998645, 0.32325317, 0.75356854],
        [0.63949937, 0.96522036, 0.37698761, 0.19822993, 0.21686278],
        [0.47732601, 0.70191641, 0.36576943, 0.871987  , 0.60707819],
        [0.72055784, 0.85820374, 0.41650474, 0.30882069, 0.02523435]],

       [[0.63557202, 0.47531608, 0.68574228, 0.46802904, 0.45896799],
        [0.35525293, 0.7286181 , 0.27542688, 0.79596555, 0.69991713],
        [0.75399323, 0.13419727, 0.74885669, 0.797986  , 0.72430541],
        [0.9337091 , 0.65222712, 0.21163259, 0.86402909, 0.62858197]],

       [[0.23475101, 0.44781748, 0.7726685 , 0.21958662, 0.13554569],
        [0.69411416, 0.93179316, 0.45021629, 0.85934705, 0.98835842],
        [0.94683049, 0.54386121, 0.38341071, 0.11877108, 0.49660307],
        [0.06932538, 0.90723338, 0.20540629, 0.41046241, 0.8254875 ]]])

In [62]:
sn = np.random.randn(3, 4, 5)
sn

array([[[ 0.61754562,  0.40000781, -1.53856056, -1.06713378,
          1.89910142],
        [-0.76902799,  1.28029959, -0.0473695 ,  0.15834418,
          1.64715768],
        [-0.02074389,  1.55554144,  0.48740163, -0.26814541,
          0.26811929],
        [ 0.42288208, -0.11304909,  0.35404204,  1.10856114,
         -1.1779697 ]],

       [[-0.18796046,  0.73585102, -1.30225648, -0.29629246,
          1.09200775],
        [-1.02191501,  0.33261604,  0.43561962, -1.50909597,
          0.5958784 ],
        [ 0.418103  ,  0.36147295, -0.04660901,  0.13174199,
         -1.85570363],
        [ 0.88973356, -0.98075213, -1.4523482 , -0.64785146,
          0.9429462 ]],

       [[ 0.08598231, -1.08526072, -1.72306161,  0.73521604,
          2.47963714],
        [ 0.7492549 , -0.69819337,  1.73547477,  0.23088043,
          1.27308694],
        [-0.9694361 , -0.22368057, -2.02313923, -0.49261432,
          1.23588075],
        [ 1.29579684, -0.10823798, -0.64290391,  0.15623927,
         -1

In [63]:
b = np.random.randint(100, 200, (3, 4))

In [64]:
b

array([[122, 102, 139, 155],
       [181, 136, 191, 145],
       [154, 153, 183, 140]])

In [65]:
np.random.seed(10)
np.random.randint(100, 200, (3, 4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [66]:
a = np.random.randint(100, 200, (3, 4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [67]:
np.random.shuffle(a)
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [68]:
np.random.shuffle(a)
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [69]:
a = np.random.randint(100, 200, (3, 4))
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [70]:
np.random.permutation(a)

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [71]:
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [72]:
np.random.permutation(a)

array([[131, 157, 136, 127],
       [113, 192, 186, 130],
       [130, 189, 112, 165]])

In [73]:
b = np.random.randint(100, 200, (8,))

In [74]:
b

array([123, 194, 111, 128, 174, 188, 109, 115])

In [75]:
np.random.choice(b, (3, 2), replace=False)

array([[188, 174],
       [115, 194],
       [128, 109]])

In [76]:
np.random.choice(b, (3, 2), p = b/np.sum(b))

array([[174, 174],
       [109, 194],
       [109, 111]])

In [77]:
u = np.random.uniform(0, 10, (3, 4))
u

array([[7.54647692, 2.95961707, 8.8393648 , 3.25511638],
       [1.65015898, 3.92529244, 0.93460375, 8.21105658],
       [1.5115202 , 3.84114449, 9.44260712, 9.87625475]])

In [78]:
n = np.random.normal(10, 5, (3, 4))
n

array([[16.41138338,  9.14097309, 12.8882903 ,  2.6251256 ],
       [10.39394227, 14.59206826,  7.5365132 , 10.48231186],
       [ 6.73620032,  8.89118781,  4.65856717,  3.86153973]])

In [79]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
np.sum(a)

105

In [81]:
np.mean(a, axis=1)

array([ 2.,  7., 12.])

In [82]:
np.mean(a, axis=0)

array([5., 6., 7., 8., 9.])

In [83]:
np.average(a, axis=0, weights=[10, 5, 1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [84]:
np.std(a)

4.320493798938574

In [85]:
np.var(a)

18.666666666666668

In [86]:
b = np.arange(15, 0, -1).reshape(3, 5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [88]:
b = np.arange(0, 15).reshape(3, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
b = np.arange(15, 0, -1).reshape(3, 5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [90]:
np.max(b)

15

In [91]:
np.argmax(b)

0

In [92]:
np.unravel_index(np.argmax(b), b.shape)

(0, 0)

In [93]:
np.ptp(b)

14

In [94]:
np.median(b)

8.0

In [95]:
a = np.random.randint(0, 20, (5))

In [96]:
a

array([14, 19, 15, 19, 17])

In [97]:
np.gradient(a)

array([ 5. ,  0.5,  0. ,  1. , -2. ])

In [98]:
b = np.random.randint(0, 20, (5))
b

array([18, 14, 16, 10, 17])

In [99]:
np.gradient(b)

array([-4. , -1. , -2. ,  0.5,  7. ])

In [100]:
c = np.random.randint(0, 50, (3, 5))
c

array([[32, 17, 41, 16, 41],
       [26, 12, 30, 17, 17],
       [16,  0, 31, 37,  9]])

In [101]:
np.gradient(c)

[array([[ -6. ,  -5. , -11. ,   1. , -24. ],
        [ -8. ,  -8.5,  -5. ,  10.5, -16. ],
        [-10. , -12. ,   1. ,  20. ,  -8. ]]),
 array([[-15. ,   4.5,  -0.5,   0. ,  25. ],
        [-14. ,   2. ,   2.5,  -6.5,   0. ],
        [-16. ,   7.5,  18.5, -11. , -28. ]])]

In [102]:
clear

In [103]:
from PIL import Image
import numpy as np
im = np.array(Image.open("Desktop/beijing.jpg"))

In [105]:
print(im.shape, im.dtype)

(669, 1012, 3) uint8


In [106]:
a = np.array(Image.open("Desktop/fcity.jpg"))
print(a.shape, a.dtype)

(441, 634, 3) uint8


In [107]:
b = [255, 255, 255] - a
im = Image.fromarray(b.astype('uint8'))
im.save("Desktop/fcity2.jpg")

In [113]:
a = np.array(Image.open("Desktop/fcity.jpg").convert('L'))
a

array([[114, 114, 114, ..., 122, 124, 114],
       [114, 114, 114, ..., 122, 124, 114],
       [115, 115, 115, ..., 121, 124, 114],
       ...,
       [194, 193, 192, ...,  40,  43,  45],
       [193, 187, 184, ...,  39,  44,  46],
       [191, 186, 181, ...,  43,  46,  49]], dtype=uint8)

In [114]:
b = 255 - a
im = Image.fromarray(b.astype('uint8'))
im.save("Desktop/fcity3.jpg")

In [115]:
a = np.array(Image.open("Desktop/fcity.jpg").convert('L'))
c = (100/255)*a + 150  # 区间变换
im = Image.fromarray(c.astype('uint8'))
im.save("Desktop/fcity4.jpg")

In [116]:
d = 255 * (a/255)**2  # 像素平方
im = Image.fromarray(d.astype('uint8'))
im.save("Desktop/fcity5.jpg")